name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.9.0'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Upload Playwright report
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/
